config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'
  get 'musics/index'
  get 'musics/search'
  root 'musics#index'
  resources :messages,only: [:new,:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :musics
end

app/models/music.rb
class Music < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :search_music, only: [:index, :search]
  def index
    @musics = Music.all
    set_music_column
    set_category_column
  end

  def search
    @results = @p.result.includes(:category)
  end

  private

  def search_music
    @p = Music.ransack(params[:q])  # 検索オブジェクトを生成
  end

  def set_music_column
    @music_name = Music.select("name").distinct  # 重複なくnameカラムのデータを取り出す
    @music_lyricist = Music.select("lyricist").distinct
    @music_year = Music.select("year").distinct
    @music_position = Music.select("position").distinct
  end

  def set_category_column
    @category_name = Category.select("name").distinct
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clarisapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/musics/index.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      ClariS Music Shearing
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
    <%= search_form_for @p, url: musics_search_path do |f| %>
    <%= f.label :name_eq, '曲名' %>
    <%= f.collection_select :name_eq, @music_name, :name, :name, include_blank: '指定なし' %>
    <br>
    <%= f.label :size_eq, '作詞家' %>
    <%= f.collection_select :lyricist_eq, @music_lyricist, :lyricist, :lyricist, include_blank: '指定なし'%>
    <br>
    <%= f.label :year_eq, 'リリース' %>
    <%= f.collection_select :year_eq, @music_year, :year, :year, include_blank: '指定なし'%>
   <br>
   <%= f.label :position_eq, 'ポジション' %>
   <%= f.collection_select :position_eq, @music_position, :position, :position, include_blank: '指定なし'%>
   <br>
   <%= f.label :category_name_eq, '作曲家' %>
   <%= f.collection_select :category_name_eq, @category_name, :name, :name, include_blank: '指定なし' %>
   <br>
    <br>
    <%= f.submit '検索' %>
    </div>
  </div>
</div>

<div class="messages">
     

<% end %>

app/views/musics/search.html.erb
<h1>
  検索結果
</h1>
<% if @results.length !=0 %>
  <% @results.each do |result| %>
    <td>
    <br>
    <li>
    <%= result.name %>
    <%= result.lyricist %>
    <%= result.year %>
    <%= result.position %>
    <%= result.category.name %>
    <%= link_to 'Sharing Roomへ', new_message_path %>
    </li>
  <% end %>
<% else %>
  該当する楽曲なし
<% end %>
<br>
<%= link_to 'トップページへ戻る', root_path %>